# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - DrHan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore DrHan.sln

      - name: Build with dotnet
        run: dotnet build DrHan.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test DrHan.sln --no-build --configuration Release --verbosity normal

      - name: Publish application
        run: dotnet publish DrHan/DrHan.csproj -c Release -o ./publish --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DrHan'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4B3BD07C44F44E96BD99F3DDDA74363D }}
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}
          ConnectionStrings__Redis: ${{ secrets.REDIS_CONNECTION_STRING }}
          JWT__Secret: ${{ secrets.JWT_SECRET }}
          Email__SmtpPassword: ${{ secrets.SMTP_PASSWORD }}
          Firebase__ApiKey: ${{ secrets.FIREBASE_API_KEY }}
          Firebase__ProjectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          ASPNETCORE_ENVIRONMENT: Production